# Generated by Django 5.2.5 on 2025-12-21 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_agentprofile_marketdemandsuggestion_salestransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Two-wheeler'), ('auto', 'Auto-rickshaw'), ('car', 'Car'), ('truck', 'Truck')], default='bike', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('current_location', models.CharField(blank=True, help_text='City/Area of operation', max_length=255)),
                ('avg_delivery_time_hours', models.PositiveIntegerField(default=24, help_text='Estimated delivery time in hours')),
                ('success_delivery_rate', models.FloatField(default=95.0, help_text='Percentage of successful deliveries')),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], default='not_assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('failed_reason', models.TextField(blank=True, help_text='Reason if delivery failed')),
                ('last_location', models.CharField(blank=True, max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='store.deliverypartner')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('packed', 'Packed & Ready'), ('picked_up', 'Picked Up by Delivery Partner'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('return_initiated', 'Return Initiated'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received')], max_length=30)),
                ('stage_timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, help_text='Location at this stage', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this stage')),
                ('image', models.ImageField(blank=True, help_text='Photo proof if applicable', null=True, upload_to='tracking/')),
                ('order_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_stages', to='store.orderdelivery')),
            ],
            options={
                'verbose_name_plural': 'Delivery Tracking',
                'ordering': ['stage_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(choices=[('defective', 'Defective/Damaged'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not as Described'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=30)),
                ('return_description', models.TextField(help_text='Detailed reason for return')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected'), ('in_transit', 'Return In Transit'), ('received', 'Return Received'), ('refunded', 'Refunded')], default='requested', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('agent_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='store.orderitem')),
                ('return_delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_request', to='store.orderdelivery')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
