# Generated by Django 5.2.5 on 2025-12-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_deliverypartner_orderdelivery_deliverytracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='company_banner',
            field=models.ImageField(blank=True, help_text='Company banner image', null=True, upload_to='agent/banners/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='agent/logos/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='trademark_image',
            field=models.ImageField(blank=True, help_text='Trademark or certification image', null=True, upload_to='agent/trademarks/'),
        ),
    ]
