# Generated by Django 5.2.5 on 2025-12-22 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_agentdeliverypartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Primary contact person name', max_length=200),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Two-wheeler'), ('auto', 'Auto-rickshaw'), ('car', 'Car'), ('truck', 'Truck'), ('van', 'Van')], max_length=50)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(blank=True, help_text='Vehicle model/name', max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('capacity', models.CharField(blank=True, help_text='e.g., 50kg, 100kg', max_length=100)),
                ('insured', models.BooleanField(default=False)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='store.deliverypartner')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-status', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='store.vehicle'),
        ),
    ]
