# Generated by Django 5.2.5 on 2026-01-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'activation', 'contact_admin')", max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('activation', 'Account Activation'), ('contact_admin', 'Contact Form to Admin'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome Email')], max_length=50)),
                ('subject', models.CharField(help_text='Email subject. Use variables like {username}, {email}, etc.', max_length=200)),
                ('body', models.TextField(help_text='Email body template. Available variables depend on template type:\n        \nActivation: {username}, {email}, {user_id}, {activation_link}\nContact Admin: {name}, {email}, {phone}, {subject_input}, {message}\nPassword Reset: {username}, {email}, {reset_link}\nWelcome: {username}, {email}\n        ')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
    ]
