# Generated by Django 5.2.5 on 2026-02-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_category_user_otp_user_otp_expiry_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_height',
            field=models.IntegerField(default=0, help_text='Logo height in pixels. Set to 0 for auto.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_width',
            field=models.IntegerField(default=200, help_text='Logo width in pixels. Set to 0 for auto.'),
        ),
    ]
