# Generated by Django 5.2.5 on 2026-02-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_sitesettings_logo_height_sitesettings_logo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_bestseller_subtitle',
            field=models.CharField(default='Amazon global bestselling products', help_text='Subtitle for best seller section', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_bestseller_title',
            field=models.CharField(default='Best Sellers Shop', help_text='Title for best seller section', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_trending_subtitle',
            field=models.CharField(default='Popular Item in the market', help_text='Subtitle for trending section', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_trending_title',
            field=models.CharField(default='Trending Product', help_text='Title for trending section', max_length=200),
        ),
    ]
