# Generated by Django 5.2.5 on 2026-02-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_sitesettings_home_bestseller_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Keywords (comma separated)', max_length=255)),
                ('dashboard_welcome_title', models.CharField(default='Agent Dashboard', max_length=200)),
                ('add_product_button_label', models.CharField(default='Add New Product', max_length=50)),
                ('products_table_header', models.CharField(default='Your Products', max_length=100)),
            ],
            options={
                'verbose_name': 'Agent Page Settings',
                'verbose_name_plural': 'Agent Page Settings',
            },
        ),
        migrations.CreateModel(
            name='AuthPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Keywords (comma separated)', max_length=255)),
                ('login_title', models.CharField(default='Login to your account', max_length=200)),
                ('register_title', models.CharField(default='Create an Account', max_length=200)),
                ('login_banner_text', models.TextField(default='New to our website?')),
                ('register_banner_text', models.TextField(default='Already have an account?')),
            ],
            options={
                'verbose_name': 'Auth Page Settings',
                'verbose_name_plural': 'Auth Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Keywords (comma separated)', max_length=255)),
                ('map_url', models.URLField(blank=True, help_text='Google Maps Embed URL', max_length=500)),
                ('contact_title', models.CharField(default='Contact Us', max_length=200)),
                ('success_message', models.TextField(default='Message sent successfully!')),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Keywords (comma separated)', max_length=255)),
                ('trending_title', models.CharField(default='Trending Product', max_length=200)),
                ('trending_subtitle', models.CharField(default='Popular Item in the market', max_length=200)),
                ('best_seller_title', models.CharField(default='Best Sellers Shop', max_length=200)),
                ('best_seller_subtitle', models.CharField(default='Amazon global bestselling products', max_length=200)),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ProductPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Keywords (comma separated)', max_length=255)),
                ('add_to_cart_label', models.CharField(default='Add to Cart', max_length=50)),
                ('out_of_stock_label', models.CharField(default='Out of Stock', max_length=50)),
                ('description_tab_label', models.CharField(default='Description', max_length=50)),
                ('reviews_tab_label', models.CharField(default='Reviews', max_length=50)),
            ],
            options={
                'verbose_name': 'Product Page Settings',
                'verbose_name_plural': 'Product Page Settings',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='GA Measurement ID (e.g., G-XXXXXXXXXX)', max_length=50),
        ),
    ]
