# Generated by Django 5.2.5 on 2026-02-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_productmedia_productreview_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, default='', help_text='Full Privacy Policy text. Standard HTML or plain text.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', help_text='Full Terms and Conditions text. Standard HTML or plain text.'),
        ),
    ]
