# Generated by Django 5.2.5 on 2026-02-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_sitesettings_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Email body template. Available variables depend on template type:\n        \nActivation: {username}, {email}, {user_id}, {activation_link}\nContact Admin: {name}, {email}, {phone}, {subject_input}, {message}\nPassword Reset: {username}, {email}, {reset_link}\nWelcome: {username}, {email}\nOTP Verification: {username}, {otp}, {logo_url}, {site_title}\n        '),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('activation', 'Account Activation'), ('contact_admin', 'Contact Form to Admin'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome Email'), ('otp_verification', 'OTP Verification')], max_length=50),
        ),
    ]
